export const browserCoreExamples = [
  "AGENT browser status",
  "AGENT browser start",
  "AGENT browser stop",
  "AGENT browser tabs",
  "AGENT browser open https://example.com",
  "AGENT browser focus abcd1234",
  "AGENT browser close abcd1234",
  "AGENT browser screenshot",
  "AGENT browser screenshot --full-page",
  "AGENT browser screenshot --ref 12",
  "AGENT browser snapshot",
  "AGENT browser snapshot --format aria --limit 200",
  "AGENT browser snapshot --efficient",
  "AGENT browser snapshot --labels",
];

export const browserActionExamples = [
  "AGENT browser navigate https://example.com",
  "AGENT browser resize 1280 720",
  "AGENT browser click 12 --double",
  'AGENT browser type 23 "hello" --submit',
  "AGENT browser press Enter",
  "AGENT browser hover 44",
  "AGENT browser drag 10 11",
  "AGENT browser select 9 OptionA OptionB",
  "AGENT browser upload /tmp/file.pdf",
  'AGENT browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "AGENT browser dialog --accept",
  'AGENT browser wait --text "Done"',
  "AGENT browser evaluate --fn '(el) => el.textContent' --ref 7",
  "AGENT browser console --level error",
  "AGENT browser pdf",
];
